[package]
name = "insecure_password_download"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.15.0"
md5 = "0.7.0"
rocket = { version = "0.5", features = ["json"] }

cookie = "0.18"
des = "0.8"
hex = "0.4"
generic-array = "0.14"
cipher = { version = "0.4", features = ["block-padding", "alloc"] }
rocket-session-store = "0.2.1"

oracle = "0.6.3"

chksum-hash-md5 = "0.0.1"
mongodb = "3.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

sqlx = { version = "0.7.0", features = [ "runtime-async-std", "sqlite", "postgres" ] }

ldap3 = "0.11.5"

tokio = { version = "1", features = ["full"] }


isahc = "1"
http = "0.2"

sxd-xpath = "0.4.2"
sxd-document = "0.3.2"

unsafe-libyaml = "0.2"

rocket_cors = "0.6.0"